Gemfile
Gemfile.lock
README.md
config.rb
script/release

Deployment

---

source/includes/rest/_broadcasts.md
source/includes/rest/_campaigns.md
source/includes/rest/_conversions.md
source/includes/rest/_workflows.md

Document arguments

---

source/includes/rest/_accounts.md
source/includes/rest/_batch_api.md
source/includes/rest/_broadcasts.md
source/includes/rest/_campaigns.md
source/includes/rest/_conversions.md
source/includes/rest/_custom_fields.md
source/includes/rest/_events.md
source/includes/rest/_forms.md
source/includes/rest/_purchases.md
source/includes/rest/_subscribers.md
source/includes/rest/_tags.md
source/includes/rest/_users.md
source/includes/rest/_webhooks.md
source/includes/rest/_workflows.md
source/index.html.md
source/javascripts/all.js

Ruby examples

---

source/includes/rest/_accounts.md
source/includes/rest/_batch_api.md
source/includes/rest/_broadcasts.md
source/includes/rest/_campaigns.md
source/includes/rest/_conversions.md
source/includes/rest/_custom_fields.md
source/includes/rest/_events.md
source/includes/rest/_forms.md
source/includes/rest/_purchases.md
source/includes/rest/_subscribers.md
source/includes/rest/_tags.md
source/includes/rest/_users.md
source/includes/rest/_webhooks.md
source/includes/rest/_workflows.md
source/index.html.md

JS Examples

---

source/includes/js/_campaign_subscriptions.md
source/includes/js/_identify.md
source/includes/js/_track.md
source/includes/rest/_authentication.md
source/includes/rest/_broadcasts.md
source/includes/rest/_campaigns.md
source/includes/rest/_forms.md
source/includes/rest/_purchases.md
source/includes/rest/_tags.md
source/index.html.md

Corrections

---

source/layouts/layout.erb

Josh Lauer requested Google Tag Manager be added to the api docs

add GTM code

---

source/includes/rest/_conversions.md
source/includes/rest/_events.md

For: https://github.com/DripEmail/drip/issues/8616

Add limits for conversion events

---

source/includes/rest/_orders.md

Help out customers, as in https://github.com/DripEmail/drip-ruby/issues/44

Add Ruby order examples

---

source/includes/rest/_campaigns.md

Fixes https://dripcom.atlassian.net/browse/DE-393

remove email stats

---

source/includes/js/_identify.md

https://dripcom.atlassian.net/browse/DE-692

DE-692 Remove reference to insecure identify response fields

---

source/includes/rest/_subscribers.md

Documentation for https://github.com/DripEmail/drip/pull/11888

document visitor_uuid options

---

source/includes/shopper_activity/_cart_activity.md

https://dripcom.atlassian.net/browse/DE-2063
https://dripcom.atlassian.net/browse/DE-1947
Small updates to docs, per the two tickets above. Updates the example to use a Drip branded example with working image and adds a link to the KB.

update example; add kb link

---

source/includes/rest/_batch_api.md
source/includes/shopper_activity/_order_activity.md

Use `{ "action": "placed" }` instead of `{ "action": "created" }` in API examples to be consistent with description.

Update Shopper Activity API Orders examples

---

source/includes/shopper_activity/_order_activity.md
source/includes/shopper_activity/_product_activity.md

https://dripcom.atlassian.net/browse/DE-2575
https://dripcom.atlassian.net/browse/DE-2575
These two tickets were both small changes to the docs, so I put them in one PR.
NB: deploy after https://github.com/DripEmail/shopper-activity/pull/158

Product delete updates

---

source/includes/shopper_activity/_cart_activity.md
source/includes/shopper_activity/_order_activity.md
source/includes/shopper_activity/_product_activity.md

Add changes from https://github.com/DripEmail/drip-ruby/pull/59 to docs.

Add examples for shopper activity ruby

---

source/includes/rest/_batch_api.md

Missed this on the first round: https://github.com/DripEmail/api-docs/pull/59
Blocked by getting a fix out to make this actually work: https://github.com/DripEmail/drip-ruby/pull/66

Shopper activity ruby batch api docs

---

source/includes/rest/_batch_api.md

https://dripcom.atlassian.net/browse/DE-2817
Add product batch docs

DE-2817 product batch docs

---

source/includes/rest/_batch_api.md
source/includes/rest/_campaigns.md
source/includes/rest/_orders.md
source/includes/rest/_subscribers.md
source/includes/rest/_webhook_events.md
source/includes/rest/_workflows.md

Contact info is now a first-class citizen (just like email) for subscribers.

Update API docs for ECRM fields

---

source/includes/rest/_subscribers.md

Addresses [PL-94](https://dripcom.atlassian.net/browse/PL-94)
Documentation to support this change: https://github.com/DripEmail/drip/pull/14077
I'm happy to update this to suit our documentation style if people think it could be improved.

Note about 429 error to sub v2 create or update endpoint

---

source/includes/rest/_subscribers.md

Follow up to be deployed after https://github.com/DripEmail/drip/pull/14622.

add 'status' argument

---

source/includes/rest/_batch_api.md
source/includes/rest/_orders.md
source/includes/rest/_workflows.md
source/includes/shopper_activity/_cart_activity.md

Outstanding minor updates

---

source/includes/rest/_subscribers.md
source/includes/shopper_activity/_cart_activity.md
source/includes/shopper_activity/_order_activity.md

Addresses [ECI-912](https://dripcom.atlassian.net/browse/ECI-912)
This documents the `initial_status` field for subscribers, cart activity, and order activity.

[ECI-912] Document initial_status field 

---

source/includes/rest/_webhook_events.md

Companion to https://github.com/DripEmail/drip/pull/24210/files

SMS-780: Add new event to API docs

---

source/includes/rest/_webhooks.md
source/includes/rest/_workflows.md

https://dripcom.atlassian.net/browse/GG-164

[GG-164] add some missing version numbers

---

source/includes/rest/_events.md

Fixes issue in this Slack thread: https://getdrip.slack.com/archives/C045YMJ143A/p1684415306622149
I confirmed that this doc change looks good locally

Update JS example code to correspond with current API

---

source/includes/js/_getting_started.md

Document a new feature to limit cookies to a path.

Limit cookies to path
